[package]
name = "aaac-dummymodule"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# CHANGED: Use ../../ because we are inside modules/ folder
aaac-interface = { path = "../../aaac-interface" }